version: '3.8'

services:
  api:
    build:
      context: .
      target: development
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - .:/src
      - /src/bin
      - /src/obj

  api-prod:
    build:
      context: .
      target: production
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production